// <auto-generated />
using System;
using GaleriAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaleriAPI.Migrations
{
    [DbContext(typeof(GaleriDbContext))]
    [Migration("20230910113957_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaleriAPI.Data.Tablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ResminYapilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ressam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tablolar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ResminYapilmaTarihi = new DateTime(1950, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ressam = "Pablo Picasso"
                        },
                        new
                        {
                            Id = 2,
                            ResminYapilmaTarihi = new DateTime(1496, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ressam = "Leonardo da Vinci"
                        },
                        new
                        {
                            Id = 3,
                            ResminYapilmaTarihi = new DateTime(1972, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ressam = "Salvador Dali"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
